### ISSUE TITLE
init(false) doesn't hide the modal

### ISSUE THREAD

**Issue by ncou** [fpmweb/modalLoading#1]
Hi,

I can't hide the modal once it's displayed.

I tryed with .init(true) and .init(false) but it doesn't hide the overlay div.

Looked in the code, there is no hide code in the .js file.

What i am missing ?

Thank you for your help.

**Comment by thembamah** [comment]
Yes, .init(true) and .init(false) don't seem to hide modal.  Try hiding it manually using jquery with the following.
 $('.modalDialog').css('display' , 'none');

**Comment by ncou** [comment]
thank you for your answer, i switched for a more robust modal loading function.
